[package]
name = "cv-andi"
version = "0.1.0"
description = "Online CV Website - ANDI FARREL AL-FAIZY"
license = "MIT"

[dependencies]
"sharrattj/elixir" = "^1.14"

[[command]]
name = "script"
module = "sharrattj/elixir:elixir"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["-S", "mix", "phx.server"]
env = ["MIX_ENV=prod"]

[fs]
"/app" = "."
